/*! (C) Ionic, https://ionicframework.com/ - Mit License */
(function(x){"use-strict";function q(a){return void 0!==a&&null!==a}function I(a){return"string"===typeof a||"number"===typeof a}function Z(a){return a.replace(/-([a-z])/g,function(a){return a[1].toUpperCase()})}function aa(a){return a.replace(/([A-Z])/g,function(a){return"-"+a[0].toLowerCase()})}function O(){}function J(a,b,c,e,f){return{c:a,b:b,i:c,f:e,a:f,o:void 0===b?void 0:b.key}}function P(a,b,c){a.$="http://www.w3.org/2000/svg";if("foreignObject"!==c&&void 0!==b)for(a=0;a<b.length;++a)c=b[a].b,void 0!==
c&&P(c,b[a].i,b[a].c)}function K(a,b,c){var e={},f,d,h=void 0;a.nodeType&&(h=a);void 0!==c?(e=b,c&&c.constructor===Array?f=c:I(c)?d=c:c&&c.c&&(f=[c])):void 0!==b&&(b&&b.constructor===Array?f=b:I(b)?d=b:b&&b.c?f=[b]:e=b);if(f&&f.constructor===Array)for(b=0;b<f.length;++b)I(f[b])&&(f[b]=J(void 0,void 0,void 0,f[b]));"s"!==a[0]||"v"!==a[1]||"g"!==a[2]||3!==a.length&&"."!==a[3]&&"#"!==a[3]||P(e,f,a);return J(a,e,f,d,h)}function ba(a,b){if("child"===b)return a.firstElementChild;if("parent"===b){if(a.parentElement)return a.parentElement;
if(a.parentNode&&a.parentNode.host)return a.parentNode.host}return"body"===b?a.ownerDocument.body:"document"===b?a.ownerDocument:"window"===b?a.ownerDocument.defaultView:a}function ca(a){return"enter"===a?13:"escape"===a?27:"space"===a?32:"tab"===a?9:null}function da(a,b,c,e){if(a&&a.$meta){var f=a.$meta.listeners;if(f)for(var d=a.h=a.h||{},h=Object.keys(f),g=0;g<h.length;g++){var k=h[g],p=f[k];if(p.B===b){c&&!d[b]?d[b]=Q(a.$el,e?e+":"+b:b,a[k].bind(a),p):!c&&d[b]&&(d[b](),delete a.h[b]);break}}}}
function Q(a,b,c,e){if(!a)return O;null===L&&(L=ea(a));var f=L?{capture:!!e.capture,passive:!!e.passive}:!!e.capture;e=b.split(":");1<e.length&&(a=ba(a,e[0]),b=e[1]);e=b.split(".");if(1<e.length){b=e[0];var d=ca(e[1]);if(null!==d){var h=c;c=function(a){a.keyCode===d&&h(a)}}}a.addEventListener(b,c,f);return function(){a&&a.removeEventListener(b,c,f)}}function ea(a){var b=!1;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0}});a.addEventListener("test",null,c)}catch(e){}return b}function R(a,
b){var c,e,f=b.a;a=a.b.attrs;var d=b.b.attrs;if((a||d)&&a!==d){a=a||{};d=d||{};for(c in d)b=d[c],e=a[c],e!==b&&("boolean"===typeof b?b?f.setAttribute(c,""):f.removeAttribute(c):120!==c.charCodeAt(0)?f.setAttribute(c,b):58===c.charCodeAt(3)?f.setAttributeNS("http://www.w3.org/XML/1998/namespace",c,b):58===c.charCodeAt(5)?f.setAttributeNS("http://www.w3.org/1999/xlink",c,b):f.setAttribute(c,b));for(c in a)c in d||f.removeAttribute(c)}}function S(a,b){var c,e=b.a;a=a.b["class"];var f=b.b["class"];if((a||
f)&&a!==f){a=a||{};f=f||{};for(c in a)f[c]||e.classList.remove(c);for(c in f)if(b=f[c],b!==a[c])e.classList[b?"add":"remove"](c)}}function T(a,b,c){if("function"===typeof a)a.call(b,c,b);else if("object"===typeof a)if("function"===typeof a[0])if(2===a.length)a[0].call(b,a[1],c,b);else{var e=a.slice(1);e.push(c);e.push(b);a[0].apply(b,e)}else for(b=0;b<a.length;b++)T(a[b])}function fa(){return function b(c){var e=b.ba,f=c.type,d=e.b.on;d&&d[f]&&T(d[f],e,c)}}function M(a,b){var c=a.b.on,e=a.listener,
f=a.a,d=b&&b.b.on,h=b&&b.a,g;if(c!==d){if(c&&e)if(d)for(g in c)d[g]||f.removeEventListener(g,e,!1);else for(g in c)f.removeEventListener(g,e,!1);if(d)if(a=b.listener=a.listener||fa(),a.ba=b,c)for(g in d)c[g]||h.addEventListener(g,a,!1);else for(g in d)h.addEventListener(g,a,!1)}}function U(a,b){var c,e,f=b.a;a=a.b.props;var d=b.b.props;if((a||d)&&a!==d){a=a||{};d=d||{};for(c in a)d[c]||delete f[c];for(c in d)b=d[c],e=a[c],e===b||"value"===c&&f[c]===b||(f[c]=b)}}function H(a,b){return a.o===b.o&&a.c===
b.c}function N(a){var b,c;if(void 0!==a.b&&(M(a),void 0!==a.i))for(c=0;c<a.i.length;++c)b=a.i[c],null==b||"string"===typeof b||N(b)}function V(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},e=c["class"]=c["class"]||{},f=a.mode,d=a.color;e[b]=!0;f&&(e[b+"-"+f]=!0,d&&(e[b+"-"+d]=e[b+"-"+f+"-"+d]=!0));return c}function ga(a,b,c,e){if("function"!==typeof a.CustomEvent){var f=function(a,b){b=b||{bubbles:!1,cancelable:!1,detail:void 0};var d=document.createEvent("CustomEvent");d.initCustomEvent(a,
b.bubbles,b.cancelable,b.detail);return d};f.prototype=a.Event.prototype;a.CustomEvent=f}return{theme:V,emit:function(d,c){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};void 0===e.composed&&(e.composed=!0);d&&d.$el&&d.$el.dispatchEvent(new a.CustomEvent((b||"")+c,e))},listener:{enable:da},controllers:{},dom:e,V:c}}function W(a){switch(a){case "0":return"default";case "1":return"ios";case "2":return"md";case "3":return"wp"}return a}function ha(a,b,c,e,f,d,h,g){var k={};Object.keys(h).forEach(function(p){function v(){return k[p]}
function m(d){k[p]!==d&&(k[p]=d,l&&l(d),X(a,b,c,e,f))}var l=g[p]?d[g[p].W].bind(d):null;k[p]=ia(b,e,d,h[p].type,p);Object.defineProperty(e,p,{configurable:!0,get:v,set:m});Object.defineProperty(d,p,{configurable:!0,get:v,set:m})})}function ia(a,b,c,e,f){return void 0!==b[f]?b[f]:void 0!==c[f]?c[f]:0===e?a.getBoolean(f):1===e?a.getNumber(f):a.get(f)}function X(a,b,c,e,f){e.J||(e.J=!0,a.nextTick(function(){var d=a.X(f),h=!1,g=e.u;g||(g=e.u=new d.U,g.$el=e,g.$meta=d,ha(a,b,c,e,f,g,d.props,d.L),a.M(e,
d,g),h=!0);if(d.C){var k=g,p=g.j?g.j:e,v=g.w,m=g,l=d.Y,n=m.render&&m.render();n?n.a=v:n=K(v,K("div",V(m,l),K("slot")));delete n.c;k.j=c(p,n)}else h&&g.render&&(k=g.render(),k.a=e,c(e,k,!0));if(h){d=d.listeners;h=g;k=Object.keys(d);for(p=0;p<k.length;p++)v=k[p],m=d[v],!1!==m.enabled&&(h.h=h.h||{},h.h[m.B]=Q(h.$el,m.B,h[v].bind(h),m));g.ionViewDidLoad&&g.ionViewDidLoad()}e.J=!1}))}function ja(a,b,c,e,f){a.nextTick(function(){var d=f.tag,h=f.l[ka(a,b,e)];h||(h=f.l.default);a.Z(h.T,function(){X(a,b,c,
e,d)})})}function ka(a,b,c){var e=c.mode;if(q(e))return e;e=a.R(c,"mode");return q(e)?e:b.get("mode","md")}var L=null,C=J("",{},[],void 0,void 0),r=x.Ionic=x.Ionic||{};r.domCtrl=function(a){function b(){f=!0;a.requestAnimationFrame(function(a){var d,g,k;try{for(d=performance.now();g=c.shift();)g(a);for(;(g=e.shift())&&!(g(a),8<performance.now()-d););}catch(p){k=p}f=!1;(c.length||e.length)&&b();if(k)throw k;})}var c=[],e=[],f=!1;return{read:function(a){c.push(a);f||b()},write:function(a){e.push(a);
f||b()},raf:a.requestAnimationFrame.bind(a)}}(x);r.nextTickCtrl=function(a){function b(){e=!1;for(var a=c.slice(0),b=c.length=0;b<a.length;b++)a[b]()}var c=[],e=!1,f=void 0,d=/iphone|ipad|ipod|ios/.test(a.navigator.userAgent.toLowerCase());if("undefined"!==typeof Promise&&-1!==Promise.toString().indexOf("[native code]"))var h=Promise.resolve(),g=function(a){console.error(a)},f=function(){h.then(b).catch(g);d&&setTimeout(O)};else f=function(){setTimeout(b,0)};return{nextTick:function(a){c.push(a);
e||(e=!0,f())}}}(x);r.configCtrl=function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};return{get:function(b){return"mode"===b?"md":a[b]?a[b]:1<arguments.length&&void 0!==arguments[1]?arguments[1]:null},getBoolean:function(b){return void 0!==a[b]?!!a[b]:1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1},getNumber:function(b){return void 0!==a[b]?a[b]:1<arguments.length&&void 0!==arguments[1]?arguments[1]:NaN}}}(r.V||{});var Y=function(a,b,c,e,f,d,h){function g(a){function d(){clearTimeout(e);
c.onerror=c.onload=null;c.parentNode.removeChild(c);delete l[a]}l[a]=!0;var c=k("script");c.charset="utf-8";c.async=!0;c.src=a;var e=setTimeout(d,12E4);c.onerror=c.onload=d;b.head.appendChild(c)}function k(a){return b.createElement(a)}var p={},v={},m={},l={},n={},q={},t=!(a.ShadyDOM&&a.ShadyDOM.inUse),w=ga(a,c.eventNamePrefix,f,d);c.loadComponents=function(a){for(var b=arguments,d=1;d<b.length;d++){var c,e=n,f=K,h=w,g=b[d],u,k=p[g[0]];k.listeners={};for(u=0;u<g[2].length;u++)c=g[2][u],k.listeners[c[0]]=
{B:c[1],capture:!!c[2],passive:!!c[3],enabled:!!c[4]};k.L={};for(u=0;u<g[3].length;u++)c=g[3][u],k.L[c[0]]={W:c[1]};k.C=!!g[4];"string"===typeof g[6]&&(u=k.l[W(g[5].toString())])&&(u.F=g[6]);g[7](e,f,h);k.U=e[g[1]];if(e=m[a]){f=0;for(h=e.length;f<h;f++)e[f]();delete m[a]}v[a]=!0}};return{aa:function(a,b){var d=b[0];b=b[1];var c={color:{},mode:{}};if(b)for(var e=0;e<b.length;e++)c[b[e][0]]={type:b[e][1]};a=p[a]={tag:a,l:{},props:c,K:[]};b=Object.keys(d);for(c=0;c<b.length;c++)a.l[W(b[c].toString())]=
{T:d[b[c]]};b=a.tag.split("-");b.shift();a.Y=b.join("-");b=Object.keys(a.props);for(c=0;c<b.length;c++)a.K.push(aa(b[c]));return a},X:function(a){return p[a]},Z:function(a,b){v[a]?b():(m[a]?m[a].push(b):m[a]=[b],a=e+"ionic."+a+".js",l[a]||g(a))},ga:function(a){return 1===a.nodeType},ha:function(a){return 3===a.nodeType},fa:function(a){return 8===a.nodeType},nextTick:h.nextTick.bind(h),O:k,P:function(a,c){return b.createElementNS(a,c)},G:function(a){return b.createTextNode(a)},N:function(a){return b.createComment(a)},
g:function(a,b,c){a.insertBefore(b,c)},v:function(a,b){a.removeChild(b)},s:function(a,b){a.appendChild(b)},I:function(a){return a.parentNode},H:function(a){return a.nextSibling},S:function(a){return(a.tagName||"").toLowerCase()},A:function(a,b){a.textContent=b},ca:function(a){return a.textContent},R:function(a,b){return a.getAttribute(b)},M:function(a,c,d){c.C&&(d.w=a.attachShadow({mode:"open"}));(a=c.l[d.mode])&&a.F&&(c.C&&t?(a.D||(a.D=k("style"),a.D.innerHTML=a.F),d.w.appendChild(a.D.cloneNode(!0))):
(c=c.tag+"."+d.mode,q[c]||(d=k("style"),d.dataset.cmpId=c,d.innerHTML=a.F.replace(/\:host\-context\((.*?)\)|:host\((.*?)\)|\:host/g,"__h"),b.head.appendChild(d),q[c]=!0)))}}}(x,x.document,r,r.staticDir,r.configCtrl,r.domCtrl,r.nextTickCtrl);(function(a,b,c,e,f){Object.keys(f||{}).forEach(function(d){class h extends HTMLElement {}var g=c.aa(d,f[d]);h.prototype.connectedCallback=function(){ja(c,e,b,this,g)};h.prototype.attributeChangedCallback=function(a,b,c){b!==c&&(a=Z(a),(b=g.props[a])&&
(this[a]=0===b.type?null===c||"false"===c?!1:!0:1===b.type?parseFloat(c):c))};h.prototype.disconnectedCallback=function(){if(this){var a=this.u;if(a){a.ionViewWillUnload&&a.ionViewWillUnload();var b=a.h;if(b){for(var c=Object.keys(b),d=0;d<c.length;d++)b[c[d]]();a.h=null}a.j&&N(a.j);this.u=a.$el=a.$meta=a.w=a.j=null}}};h.observedAttributes=g.K;a.customElements.define(d,h)})})(x,function(a){function b(b){return function(){a.v(a.I(b),b)}}function c(b,e,f,k){var d=void 0,g=b.b;void 0!==g&&q(d=g.m)&&
q(d=d.da)&&(d(b),g=b.b);var h=b.i,l=b.c;if("!"===l)void 0===b.f&&(b.f=""),b.a=a.N(b.f);else if(k&&"slot"===l)for(;e=k.shift();){a.v(e.parentNode,e);if(0===k.length)return e;a.s(f,e)}else if(void 0!==l){var n=l.indexOf("#");f=l.indexOf(".",n);var A=0<n?n:l.length,t=0<f?f:l.length,n=-1!==n||-1!==f?l.slice(0,Math.min(A,t)):l,g=b.a=q(g)&&q(d=g.$)?a.P(d,n):a.O(n);A<t&&(g.id=l.slice(A+1,t));0<f&&(g.className=l.slice(t+1).replace(/\./g," "));R(C,b);S(C,b);M(C,b);U(C,b);if(h&&h.constructor===Array)for(d=
0;d<h.length;++d)l=h[d],null!=l&&a.s(g,c(l,e,g,k));else I(b.f)&&a.s(g,a.G(b.f));d=b.b.m;q(d)&&(d.create&&d.create(C,b),d.ea&&e.push(b))}else b.a=a.G(b.f);return b.a}function e(c,e,f,k){for(;f<=k;++f){var d=void 0,g,h=e[f];null!=h&&(q(h.c)?(N(h),g=b(h.a),q(d=h.b)&&q(d=d.m)&&q(d=d.remove)?d(h,g):g()):a.v(c,h.a))}}function f(b,h,g,k){if(k||"slot"!==b.c){var d=void 0,v=void 0;q(d=h.b)&&q(v=d.m)&&q(d=v.ja)&&d(b,h);var m=h.a=b.a,l=b.i,n=h.i;if(b!==h){void 0!==h.b&&(R(b,h),S(b,h),M(b,h),U(b,h),d=h.b.m,q(d)&&
q(d=d.update)&&d(b,h));if(void 0===h.f)if(q(l)&&q(n)){if(l!==n){var A=k?[]:null;if(k)for(var t=h.a.childNodes,w=0;w<t.length;w++)A.push(t[w]);for(var m=m.shadowRoot||m,u=0,w=0,r=l.length-1,y=l[0],B=l[r],t=n.length-1,z=n[0],D=n[t],E=void 0,x,F;u<=r&&w<=t;)if(null==y)y=l[++u];else if(null==B)B=l[--r];else if(null==z)z=n[++w];else if(null==D)D=n[--t];else if(H(y,z))f(y,z,g,k),y=l[++u],z=n[++w];else if(H(B,D))f(B,D,g,k),B=l[--r],D=n[--t];else if(H(y,D))f(y,D,g,k),a.g(m,y.a,a.H(B.a)),y=l[++u],D=n[--t];
else{if(H(B,z))f(B,z,g,k),a.g(m,B.a,y.a),B=l[--r];else{if(void 0===E){var G;x=l;F=r;for(var C={},E=u;E<=F;++E)G=x[E],null!=G&&(G=G.o,void 0!==G&&(C[G]=E));E=C}x=E[z.o];void 0===x?a.g(m,c(z,g,m,A),y.a):(F=l[x],F.c!==z.c?a.g(m,c(z,g,m,A),y.a):(f(F,z,g,k),l[x]=void 0,a.g(m,F.a,y.a)))}z=n[++w]}if(u>r)for(k=null==n[t+1]?null:n[t+1].a,l=w;l<=t;++l)w=n[l],null!=w&&a.g(m,c(w,g,m,A),k);else w>t&&e(m,l,u,r)}}else if(q(n))for(q(b.f)&&a.A(m,""),A=0,k=n.length-1;A<=k;++A)l=n[A],null!=l&&a.g(m,c(l,g,m,null),null);
else q(l)?e(m,l,0,l.length-1):q(b.f)&&a.A(m,"");else b.f!==h.f&&a.A(m,h.f);q(v)&&q(d=v.ia)&&d(b,h)}}}return function(b,h,g){var d,p=[];void 0!==b.c||void 0!==b.a||(b=J(a.S(b)+(b.id?"#"+b.id:"")+(b.className?"."+b.className.split(" ").join("."):""),{},[],void 0,b));h.a||H(b,h)?f(b,h,p,g):(g=b.a,d=a.I(g),c(h,p,d,[]),null!==d&&(a.g(d,h.a,a.H(g)),e(d,[b],0,0)));return h}}(Y),Y,r.configCtrl,r.components)})(window);
